trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: jm-simphony-assessment  # Centraliza las variables

stages:
  - stage: Infrastructure
    displayName: 'Despliegue de Infraestructura'
    jobs:
      - job: TerraformDeploy
        displayName: 'Construcción de infraestructura con Terraform'
        steps:
          - template: templates/infra-template.yml

  - stage: BuildApp
    displayName: 'Compilación y ejecucion de pruebas de la Aplicación Node.js'
    dependsOn: Infrastructure
    condition: succeeded()
    jobs:
      - job: NodeBuildJob
        displayName: 'Build y Docker'
        steps:
          - template: templates/app-template.yml

  - stage: BuildDockerImage
    displayName: 'Construcción de Imagen Docker'
    dependsOn: BuildApp  
    condition: succeeded() 
    jobs:
      - job: DockerBuildJob
        displayName: 'Construcción de imagen Docker'
        steps:
          - template: templates/img-docker-template.yml          

  - stage: Release
    displayName: 'Despliegue de Aplicación'
    dependsOn: BuildDockerImage
    condition: succeeded()
    jobs:
      - job: ReleaseJob
        displayName: 'Deploy a Azure Web App'
        steps:
          - template: templates/release-template.yml